config/routes.rb
Qats::Application.routes.draw do
 

  resources :owners

   root :to => 'owners#new'

match '/about', :to => 'pages#about'
match '/contact', :to => 'pages#contact'
match '/privacy', :to => 'pages#privacy'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  attr_accessible :active, :address, :city, :country, :email, :firstname, :lastname, :phone
  validates :firstname, :lastname, :email, :phone,  :presence => true
  validates_format_of :email, :with => /^[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info|qa))$/i, :message => "Invalid Email Address"
  validates_format_of :phone, :with => /^(\d{11}|\+?\d{3}?[-.]\d{4}[-.]\d{4})$/, :message => "should be 11 digits (country code required) and delimited with dashes only"
  validates_inclusion_of :country, :in => %[QA KSA UAE], :message => "is not an option"
  COUNTRIES  = [['Qatar', 'QA'], ['Saudia Arabia', 'KSA'], ['United Arab Emirates', 'UAE']]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @owners }
    end
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @owner = Owner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/new
  # GET /owners/new.json
  def new
    @owner = Owner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @owner }
    end
  end

  # GET /owners/1/edit
  def edit
    @owner = Owner.find(params[:id])
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(params[:owner])

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: "Created new owner #{@owner.firstname} #{@owner.lastname}" } 
        format.json { render json: @owner, status: :created, location: @owner }
      else
        format.html { render action: "new" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /owners/1
  # PUT /owners/1.json
  def update
    @owner = Owner.find(params[:id])

    respond_to do |format|
      if @owner.update_attributes(params[:owner])
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner = Owner.find(params[:id])
    @owner.destroy

    respond_to do |format|
      format.html { redirect_to owners_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.select(:country, Owner::COUNTRIES) %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Address</th>
    <th>City</th>
    <th>Country</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @owners.each do |owner| %>
  <tr>
    <td><%= owner.firstname %></td>
    <td><%= owner.lastname %></td>
    <td><%= owner.address %></td>
    <td><%= owner.city %></td>
    <td><%= owner.country %></td>
    <td><%= owner.email %></td>
    <td><%= owner.phone %></td>
    <td><%= owner.active %></td>
    <td><%= link_to 'Show', owner %></td>
    <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
    <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @owner.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @owner.lastname %>
</p>

<p>
  <b>Address:</b>
  <%= @owner.address %>
</p>

<p>
  <b>City:</b>
  <%= @owner.city %>
</p>

<p>
  <b>Country:</b>
  <%= @owner.country %>
</p>

<p>
  <b>Email:</b>
  <%= @owner.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @owner.phone %>
</p>

<p>
  <b>Active:</b>
  <%= @owner.active %>
</p>


<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>About Us</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Contact Us</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Welcome to my application!"</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Our Privacy Policy</p>